In [38]:
import torch
import torch.nn as nn
import torch.optim as optim
import pytorch_lightning as pl
from sentence_transformers import SentenceTransformer
import numpy as np
from pytorch_lightning.callbacks import Callback
import pandas as pd
import pickle
from pytorch_lightning.callbacks import ModelCheckpoint

In [39]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3060 Laptop GPU'

In [40]:
items = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/books_data_with_new_id.csv')

full_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/no dup new/amazon_books_ratings_full_filtered_fixed.csv')
train_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/no dup new/amazon_books_ratings_train_filtered_fixed.csv')
val_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/no dup new/amazon_books_ratings_val_filtered_fixed.csv')
test_ratings = pd.read_csv('./processed_dataset/Amazon-Books/20 interactions fixed/no dup new/amazon_books_ratings_test_filtered_fixed.csv')

In [42]:
items = items.dropna(subset=['item_id'])

duplicated_items = items[items.duplicated(subset='item_id', keep=False)]
duplicated_items

Empty DataFrame
Columns: [Title, description, authors, image, previewLink, publisher, publishedDate, infoLink, categories, ratingsCount, item_id]
Index: []

In [45]:
def generate_user_texts_with_history(items, ratings):
    # Initialize user histories with an empty list for each unique user_id
    user_histories = {user_id: [] for user_id in ratings['user_id'].unique()}
    user_texts = []

    # Convert relevant columns to dictionaries for faster access
    items_dict = items.set_index('item_id')[['Title', 'categories', 'authors']].to_dict('index')

    for _, row in ratings.iterrows():
        user_id = row['user_id']
        item_id = row['item_id']
        profile_name = row['profileName']

        # Prepare the user's history (only the last 3 items)
        history_items = []
        for mid in user_histories[user_id][-3:]:
            if mid in items_dict:
                category = items_dict[mid]['categories']

                # Clean and format the category, ensure it is not NaN
                if pd.notna(category):
                    category = category.strip("[]'\"")

                    # Build the history string based on the available data
                    history_entry = f"{category}"

                    if history_entry:
                        history_items.append(history_entry)

        history_str = ", ".join(history_items)

        if history_str:
            combined_features = f"profileName: {profile_name} [SEP] category: {history_str}"
        else:
            combined_features = f"profileName: {profile_name}"

        user_texts.append(combined_features)

        # Update the user history after generating combined features, only if the item_id is valid
        if item_id in items_dict:
            user_histories[user_id].append(item_id)

    return user_texts

In [46]:
train_user_texts = generate_user_texts_with_history(items, train_ratings)
val_user_texts = generate_user_texts_with_history(items, val_ratings)
test_user_texts = generate_user_texts_with_history(items, test_ratings)

['profileName: Ellen C. Falkenberry "ellenf"',
 'profileName: Charles Slovenski',
 'profileName: N. Sausser "pucksau"',
 'profileName: Mary Whipple',
 'profileName: fawls@erols.com',
 'profileName: fawls@erols.com [SEP] category: Fiction',
 'profileName: fawls@erols.com [SEP] category: Fiction, Fiction',
 'profileName: Sai Li',
 'profileName: Sai Li [SEP] category: Fiction',
 'profileName: Sai Li [SEP] category: Fiction, Fiction',
 'profileName: P. Meltzer',
 'profileName: Michael Battaglia',
 'profileName: Michael Battaglia [SEP] category: Fiction',
 'profileName: Gerald Lipsky',
 'profileName: Steve Sailer',
 'profileName: nickoli@rmi.net',
 'profileName: nickoli@rmi.net [SEP] category: Fiction',
 'profileName: Mark Shanks',
 'profileName: Michael Battaglia [SEP] category: Fiction, Fiction',
 'profileName: Travis Cottreau',
 'profileName: Jonathan W. Robie',
 'profileName: Michael Battaglia [SEP] category: Fiction, Fiction, Fiction',
 'profileName: Z23Bull@Aol.com',
 'profileName: lander@rice.edu',
 'profileName: lander@rice.edu',
 'profileName: Thelma C. Johnson "doodlebug@multipro.com"',
 'profileName: lander@rice.edu [SEP] category: Totalitarianism',
 'profileName: lander@rice.edu [SEP] category: Totalitarianism, Fiction',
 'profileName: Ron "mvg@whidbey.com"',
 'profileName: Maudeen Wachsmith "BeachReader"',
 'profileName: aumannr@juno.com',
 'profileName: Ron "mvg@whidbey.com"',
 'profileName: Margaret Fiore',
 'profileName: Stan Vernooy',
 'profileName: jim.morrison@montego.com',
 'profileName: edughman@netwalk.com',
 'profileName: Matt Myford (mmyford@etsieb.com)',
 'profileName: aumannr@juno.com',
 'profileName: jim.morrison@montego.com',
 'profileName: cdunigan@hotmail.com',
 'profileName: cdunigan@hotmail.com [SEP] category: Education',
 'profileName: Matt Myford (mmyford@etsieb.com) [SEP] category: Juvenile Fiction',
 'profileName: fortune@akis.at',
 'profileName: fortune@akis.at [SEP] category: Fiction',
 'profileName: fortune@akis.at [SEP] category: Fiction, Totalitarianism',
 'profileName: David Rasquinha',
 'profileName: Finhill@ix.netcom.com',
 'profileName: Finhill@ix.netcom.com',
 'profileName: edughman@netwalk.com [SEP] category: Fiction',
 'profileName: edughman@netwalk.com [SEP] category: Fiction, Religion',
 'profileName: Sheri in Reho',
 'profileName: Finhill@ix.netcom.com [SEP] category: Brothers',
 'profileName: Bill Fleck',
 'profileName: Alan Nelson, No Chance Meetings Books &amp; O...',
 'profileName: David Graham',
 'profileName: Stephen McHenry',
 'profileName: Edward Gordon Brown',
 'profileName: Margaret Fiore [SEP] category: Comics & Graphic Novels',
 'profileName: David Graham',
 'profileName: The Chalcenteric Kid',
 'profileName: David Graham [SEP] category: Epic poetry',
 'profileName: The Chalcenteric Kid [SEP] category: Fiction',
 'profileName: Caroline P. Hampton "Project Manager + Blogge...',
 'profileName: David Graham [SEP] category: Epic poetry, Medicine',
 'profileName: David Graham [SEP] category: Epic poetry, Medicine, Fiction',
 'profileName: Alan Nelson, No Chance Meetings Books &amp; O... [SEP] category: Ethnology',
 'profileName: GojuNinja@aol.com',
 'profileName: GojuNinja@aol.com [SEP] category: Fiction',
 'profileName: GojuNinja@aol.com [SEP] category: Fiction, Fiction',
 'profileName: Eileen Galen',
 'profileName: scutler@nimbus.ocis.temple.edu',
 'profileName: Debbie Lee Wesselmann',
 'profileName: Alan Nelson, No Chance Meetings Books &amp; O... [SEP] category: Ethnology',
 'profileName: John J. Rinck',
 'profileName: John J. Rinck [SEP] category: Fiction',
 'profileName: David Graham [SEP] category: Medicine, Fiction, Fiction',
 'profileName: Robert Moore',
 'profileName: J R Zullo',
 'profileName: Robert Moore [SEP] category: Fiction',
 'profileName: Robert Moore [SEP] category: Fiction, Fiction',
 'profileName: David Graham [SEP] category: Fiction, Fiction, Fiction',
 'profileName: David Graham [SEP] category: Fiction, Fiction',
 'profileName: David Graham [SEP] category: Fiction, Fiction',
 'profileName: nickoli@rmi.net [SEP] category: Fiction',
 'profileName: Alan Nelson, No Chance Meetings Books &amp; O... [SEP] category: Ethnology, Fiction',
 'profileName: scutler@nimbus.ocis.temple.edu [SEP] category: Fables',
 'profileName: scutler@nimbus.ocis.temple.edu [SEP] category: Fables, History',
 'profileName: David Graham [SEP] category: Fiction',
 'profileName: David Graham [SEP] category: Fiction, Religion',
 'profileName: David Graham [SEP] category: Religion, Fiction',
 'profileName: John J. Rinck [SEP] category: Fiction, Fiction',
 'profileName: adead_poet@hotmail.com "adead_poet@hotmail.com"',
 'profileName: adead_poet@hotmail.com "adead_poet@hotmail.com" [SEP] category: Fiction',
 'profileName: David Graham [SEP] category: Religion, Fiction, Fiction',
 'profileName: David Graham [SEP] category: Fiction, Fiction, Fiction',
 'profileName: David Graham [SEP] category: Fiction, Fiction',
 'profileName: "donnie@dreamscape.com"',
 'profileName: Eugene G. Barnes',
 'profileName: Eugene G. Barnes',
 'profileName: Amy Tiemann "aka Mojo Mom"']

In [47]:
len(train_user_texts)

262296

In [48]:
def generate_last_user_texts_with_history(items, val_ratings):
    user_histories = {}
    last_user_texts = {}

    # Convert items to a dictionary for faster access
    items_dict = items.set_index('item_id')[['Title', 'categories', 'authors']].to_dict('index')

    # Process the val_ratings
    for _, row in val_ratings.iterrows():
        user_id = row['user_id']
        item_id = row['item_id']
        profile_name = row['profileName']  # Get the profile name directly from the ratings DataFrame

        # Initialize user history if not already done
        if user_id not in user_histories:
            user_histories[user_id] = []

        # Generate the user's history (only the last 3 items)
        history_items = []
        for mid in user_histories[user_id][-3:]:
            if mid in items_dict:
                category = items_dict[mid]['categories']

                # Clean and format the category, ensure it is not NaN
                if pd.notna(category):
                    category = category.strip("[]'\"")

                    # Build the history string based on the available data
                    history_entry = f"{category}"

                    if history_entry:
                        history_items.append(history_entry)

        history_str = ", ".join(history_items)

        # Combine history into the final text format
        if history_str:
            combined_features = f"profileName: {profile_name} [SEP] category: {history_str}"
        else:
            combined_features = f"profileName: {profile_name}"

        # Update the dictionary to keep the last text for each user
        last_user_texts[user_id] = combined_features

        # Update the user history after generating combined features
        if item_id in items_dict:  # Ensure item exists in the dictionary
            user_histories[user_id].append(item_id)

    return last_user_texts

# Generate the last user texts for the validation data
val_last_user_texts = generate_last_user_texts_with_history(items, val_ratings)

In [49]:
val_last_user_texts

{'A3RTKL9KB8KLID': 'profileName: Stan Vernooy [SEP] category: Fiction, Fiction',
 'A3TEH90X39WC8F': 'profileName: Stuart W. Mirsky "swm" [SEP] category: Fiction',
 'A3SOB0CMUBK6XJ': 'profileName: fawls@erols.com',
 'A2QBHNK9H2SVRJ': 'profileName: Angela Linton "Angie" [SEP] category: Fiction',
 'A2YUZKPLUYQDKV': 'profileName: Michael Battaglia [SEP] category: Fiction, Fiction, Fiction',
 'A3927BH5H75LII': 'profileName: Sai Li [SEP] category: Manhattan (New York, N.Y.), Fiction, Philosophy',
 'A2FR8GG77M4TP7': 'profileName: P. Meltzer [SEP] category: Computers',
 'A1GBOCJ943SP8R': 'profileName: Steve Sailer [SEP] category: Fiction',
 'AXOA9OI962P0Q': 'profileName: nickoli@rmi.net [SEP] category: Fiction',
 'ARG7WTYP8L66M': 'profileName: James Paris "Tarnmoor" [SEP] category: Blandings Castle (England : Imaginary place), Catalogs, Union',
 'A2T28ETOO7OBE': 'profileName: Travis Cottreau [SEP] category: Electronic books, Fiction, Ahab, Captain (Fictitious character)',
 'A1UMFRK5YTITOY': 'profileName: Harold L. Laroff [SEP] category: Fiction, Fiction',
 'A1IMBBVGT354MR': 'profileName: Charlton Griffin "Charlton" [SEP] category: Educational psychology',
 'A3MFEASBE913T': 'profileName: Z23Bull@Aol.com',
 'A142VB1X9G6MSQ': 'profileName: lander@rice.edu [SEP] category: Fiction, Brothers',
 'A1YZ4D7A1ZONM1': 'profileName: scutler@nimbus.ocis.temple.edu [SEP] category: Fiction',
 'ALXJB1S20SQTH': 'profileName: Casca [SEP] category: Psychology, Fiction',
 'A1LOWTY6W12Z14': 'profileName: JEFF ROBERTS [SEP] category: Fiction',
 'A2R8V33UX51IYV': 'profileName: Edwardson Tan [SEP] category: Fables',
 'A1VCG7N8BV7XWC': 'profileName: MLPlayfair [SEP] category: FICTION',
 'A3VLB9YNIK61OJ': 'profileName: Eric Brotheridge [SEP] category: Upper class',
 'A30ZPSYOGFJXR6': 'profileName: Manola Sommerfeld [SEP] category: Fiction, Fiction, Reference',
 'A2EZCA8CJS0POA': 'profileName: jim.morrison@montego.com [SEP] category: Juvenile Fiction',
 'AAA9XEKBIS3O7': 'profileName: aumannr@juno.com [SEP] category: Fiction',
 'A3G31NPX7YU7TT': 'profileName: R. B. Bernstein "R. B. Bernstein, Adjunct Pro... [SEP] category: Fiction',
 'A3N3GNVHFZZ6N1': 'profileName: Robert Derenthal "bucherwurm" [SEP] category: Fiction, Fiction, Fiction',
 'A3KLO0I1O94HQS': 'profileName: Tania "dk smilla" [SEP] category: Fiction',
 'A1JHR3ZOSYSQ9R': 'profileName: William M Miller',
 'A1PS66N855AO4D': 'profileName: cdunigan@hotmail.com [SEP] category: True Crime',
 'A2T7GJONIZFP1Q': 'profileName: Maudeen Wachsmith "BeachReader" [SEP] category: Fiction, Fiction',
 'A3PWH2V3PGIZRF': 'profileName: Matt Myford (mmyford@etsieb.com) [SEP] category: Psychology',
 'A19ZHP0U3QQ01I': 'profileName: fortune@akis.at [SEP] category: Fiction',
 'A3BR4RIE8HDY1W': 'profileName: David Rasquinha [SEP] category: American fiction, Fiction, Fiction',
 'A3N6JG64P2G9EV': 'profileName: BarkLessWagMore [SEP] category: Fiction',
 'A2JPGNKUBZB29V': 'profileName: John J. Rinck [SEP] category: Foreign Language Study',
 'A3RRQI0A7B552N': 'profileName: Finhill@ix.netcom.com',
 'A1QR4PKVPQTM': 'profileName: edughman@netwalk.com [SEP] category: Religion',
 'AATD008OTFXT1': 'profileName: Bill Fleck [SEP] category: Biography & Autobiography',
 'A82OURDM3C77O': 'profileName: Eileen Galen [SEP] category: Reference, Computers',
 'AWDFOM2D4PTZD': 'profileName: The Chalcenteric Kid [SEP] category: Fiction, Robots',
 'A1NOVRB88NSYGM': 'profileName: Eugene G. Barnes [SEP] category: Fiction, Fiction',
 'A3TLY1A7NGVCQM': 'profileName: Alexander E. Paulsen "AlexP" [SEP] category: Fiction',
 'A3AZ4O4I9S4668': 'profileName: N. Sausser "pucksau" [SEP] category: Religion, Fiction',
 'ATOFFO1VNCAGQ': 'profileName: Michael Delaware [SEP] category: Fiction, Juvenile Fiction, Fiction',
 'A3SX5KIWNH9IJD': 'profileName: P. Legerski [SEP] category: Fiction',
 'A2UDGZUEYHULS5': 'profileName: M. J. Smith [SEP] category: Fiction, Religion, Colombo (Sri Lanka)',
 'A2FAGKHE7DRFXA': 'profileName: Alan Nelson, No Chance Meetings Books &amp; O... [SEP] category: History, Ethnology, Fiction',
 'A1M2T0J45TTE64': 'profileName: G. Powell [SEP] category: Computers, Museum directors, Biography & Autobiography',
 'A16S0CNPC88RXH': 'profileName: P. Lozar "plozar" [SEP] category: Literary Criticism, Literary Criticism',
 'AGHIV0V0ON7MO': 'profileName: David Graham [SEP] category: Fiction, Christian fiction, Christianity',
 'A36MQW22BD8LJU': 'profileName: Chess Heart "paxbear" [SEP] category: Art, Juvenile Fiction',
 'A3CC7YN38MAJNV': 'profileName: GojuNinja@aol.com [SEP] category: Fiction',
 'A2CVXUY1EYQGGA': 'profileName: bobbewig [SEP] category: Fiction, Copyright',
 'A6TGXURZ5635Q': 'profileName: Michael E. Flaherty "michael@flaherty.net" [SEP] category: Fiction',
 'A16QODENBJVUI1': 'profileName: Robert Moore [SEP] category: Juvenile Fiction, History, Fiction',
 'AZGXZ2UUK6X': 'profileName: Catherine Hallberg "(Kate)" [SEP] category: Law, Children of clergy',
 'AQ2UN38CMK119': 'profileName: P. Mann [SEP] category: Detective and mystery stories, Travel',
 'A2YIMB2LF7HH1C': 'profileName: Patrick Carroll "Winebibber. Java/JEE Develo... [SEP] category: Biography & Autobiography',
 'A1E45C97JEF57H': 'profileName: Edward Alexander Gerster "miamibooks" [SEP] category: Biography & Autobiography, Gardening',
 'ALU2IJ2DZD86X': 'profileName: "donnie@dreamscape.com" [SEP] category: Fiction, Fiction',
 'A1HLJAZ1J5MMAB': 'profileName: Gerald Lipsky',
 'AGSWTH7SP2256': 'profileName: R. W. Rasband [SEP] category: Americana, Air ducts',
 'A1V359XAMSXP7Y': 'profileName: bryan12603 [SEP] category: Religion',
 'A19DJYSLM9F46K': 'profileName: Constant Weeder "batttman" [SEP] category: Fiction, Fiction',
 'A1KXONMEYYD844': 'profileName: Andrew Georgiadis [SEP] category: Fiction, Chicago (Ill.)',
 'A3AD071UEP20WS': 'profileName: Roger Long "longrush" [SEP] category: Fiction, Fiction',
 'A2QSRP25LFCQ7X': 'profileName: Pam "SMB,SLT" [SEP] category: Music',
 'A1JTG5X4VHJV27': 'profileName: Plume45 "kitka12345" [SEP] category: Fiction, Libraries',
 'A126JVOAOOR42V': 'profileName: John McConnell [SEP] category: Fiction, Travel, Self-Help',
 'A2GAV2CXWH5VOH': 'profileName: Ido Hartogsohn [SEP] category: Fiction',
 'A31YIFM5UMVH4H': 'profileName: J. K. Kelley "literary mercenary" [SEP] category: History, Fiction',
 'A293UBA80BWN1J': 'profileName: D. Cusick "scalloway"',
 'A2ATJVBXB1SR7C': 'profileName: "rhbouchard" [SEP] category: Fiction',
 'A3QR1AS4UDQZLA': 'profileName: R. Manning "Just a guy"',
 'A1EDOWER7RO6KZ': 'profileName: Pershing (pridenprej@aol.com) [SEP] category: Executions and executioners',
 'AR9IELIBGQRR1': 'profileName: L A Spillane-Larke [SEP] category: Fiction, Fiction',
 'A24Z2NMIG50EI4': 'profileName: Sarah "sssspro" [SEP] category: Religion',
 'ASNE6WU6V6P2N': 'profileName: Craig Larson',
 'ACQULNOU5ZJBP': 'profileName: Aussie Reader "&#34;Rick&#34;" [SEP] category: History, History, Oral history',
 'A9HW2IRETVL9A': 'profileName: Lenore S. Schellinger "linn556"',
 'A2HR0DJG4WMR8R': 'profileName: Maurice Williams "mauricewms" [SEP] category: Fiction, Fiction, Fiction',
 'AR2DE47VCY1C8': 'profileName: Joseph H Pierre "Joe Pierre" [SEP] category: Juvenile Fiction, Political Science',
 'A3LRARTAC0SN6C': 'profileName: Leonard L. Wilson [SEP] category: Barsetshire (England : Imaginary place), Fiction',
 'A1RPTVW5VEOSI': 'profileName: Michael J. Edelman [SEP] category: Fiction, Sports & Recreation, Juvenile Nonfiction',
 'A2S166WSCFIFP5': 'profileName: adead_poet@hotmail.com "adead_poet@hotmail.com" [SEP] category: Comics & Graphic Novels, Fiction',
 'A4P7HYSOIVBLL': 'profileName: Bonnie McKinzie [SEP] category: Christian fiction, Fiction',
 'AXCNBMLTW6HJV': 'profileName: Hairy Growler "Hairy Growler" [SEP] category: Education, Fiction',
 'A1YWUPCT83WY48': 'profileName: Claude Avary "West Coast Reader" [SEP] category: Fiction, Fiction, Fiction',
 'A3D7XC7USJ9X7J': 'profileName: henrique fleming',
 'A3CSRP3P4U9HI': 'profileName: Alan R. Holyoak [SEP] category: Church group work',
 'AL6JIT43D8D4Z': 'profileName: unraveler "unraveler" [SEP] category: Animal experimentation, Fiction',
 'A3FHSLWEMH7JD8': 'profileName: Elizabeth G. Melillo "gloriana" [SEP] category: American wit and humor, Brothers and sisters',
 'A3LEIG4U66RSQ': 'profileName: Glenn H. Reynolds "Instapundit" [SEP] category: Science',
 'A331OF34UX4Y1K': 'profileName: M. Fonseca "carmarthen" [SEP] category: Fiction, Biography & Autobiography',
 'A27Z0UB301NYF6': 'profileName: Adam Piontek "made to order" [SEP] category: Fiction',
 'AONFDJDB2741A': 'profileName: Rebecca Jordan (bikly@hotmail.com) [SEP] category: Fiction',
 'A3RT54F73Z505I': 'profileName: patnkelly@toad.net [SEP] category: Fiction, Adultery',
 'A273LW1MLEE3R9': 'profileName: EdHopper "Painter" [SEP] category: Fiction',
 'A3J7CFLNGT844W': 'profileName: Cameron B. Clark [SEP] category: Religion',
 'A1FEEFAK5Y45M2': 'profileName: CRC [SEP] category: Adultery, Books and reading, Fiction',
 'A11NMT4P8EPWKW': 'profileName: A Customer [SEP] category: Fiction, Health education',
 'A3NSSFRT20WXZ7': 'profileName: M. T. Guzman "squeakychu" [SEP] category: Juvenile Nonfiction, Fiction, Fiction',
 'A1S70GB3XGCXIF': 'profileName: Yoda510@aol.com',
 'A3TXYHARLZMKXU': 'profileName: Erica "Erica" [SEP] category: Fiction',
 'A8DJ9EU2QP2JM': 'profileName: Wayne A. Smith [SEP] category: Nature, History',
 'A3E5QO8YTWMGQ1': 'profileName: "jradoff" [SEP] category: Fiction, Fiction',
 'A3IBGS3MVB7G6U': 'profileName: vic spicer [SEP] category: Fiction, Fiction',
 'A23059WU8ZCRL5': 'profileName: . "Adelie" [SEP] category: Social Science, Fiction, History',
 'A29E0Q47E8CPPO': 'profileName: Shogun Len "tokieyasu" [SEP] category: Fiction, Fiction, Fiction',
 'A2HM0BZWQRV1EF': 'profileName: Blaine Greenfield "eclectic reader" [SEP] category: Homeopathy, Biography & Autobiography',
 'AK7CAW3N1XZV6': 'profileName: Beth Cholette "doctor_beth" [SEP] category: Fiction, Juvenile Fiction',
 'AV7ATN4TN8AQT': 'profileName: GeoX "GeoX" [SEP] category: Fiction, Doinel, Antoine (Fictitious character)',
 'A1KCZV9PDD5FF': 'profileName: Theodore G. Mihran',
 'ARYF8JUHY2S1X': 'profileName: Dianna Johnston "Compulsive Reader" [SEP] category: Fiction',
 'A2VBIFEKN2TUUO': 'profileName: Ron "mvg@whidbey.com" [SEP] category: Fiction',
 'A2ORDVE96GL3Q7': 'profileName: richard_t "richard_t" [SEP] category: History, Literary Collections, Science',
 'AOV9AIX4UE5BB': 'profileName: Marion "dragonfly80@hotmail.com" [SEP] category: Fiction, Fiction, Biography & Autobiography',
 'A2U38TE0Y06I4I': 'profileName: Andrew Rasanen [SEP] category: History',
 'A1KOJO4E89ASOY': 'profileName: J. P. Ledbetter "Jim Ledbetter Sr." [SEP] category: Political Science, Philosophy',
 'AVJUMZ26NEX7J': 'profileName: W. S. Jones "bibliophile"',
 'A2OLHSFPO070FZ': 'profileName: puffinswan "puffinswan" [SEP] category: Drama, Fiction',
 'A18FWHWSETTT0N': 'profileName: Art King [SEP] category: Religion',
 'A1AD7RTDK3EVWR': 'profileName: Kenneth G. Ramey [SEP] category: Fiction, Fiction, Cartographers',
 'A22LX6529JJ166': 'profileName: K. Johnson [SEP] category: Cooking, Language Arts & Disciplines, Biography & Autobiography',
 'AVXXGV0UD721E': 'profileName: Antonio Sacin (abreviatio@aol.com) [SEP] category: History, Religion',
 'A221VUR1PEUCI3': 'profileName: Jeanna180 "Jeanna180"',
 'A3LNZKV31R04C4': 'profileName: Betti Trapp [SEP] category: Religion',
 'A2NBOL825B93OM': 'profileName: J R Zullo [SEP] category: Audiobooks, Fiction, Discworld (Imaginary place)',
 'A2CWQW5MCYL10J': 'profileName: nobizinfla "nobizinfla" [SEP] category: Fiction, Fiction, Fiction',
 'AM836D28P0EEU': 'profileName: Frank Lynch "frank_lynch" [SEP] category: Biography & Autobiography, Great Plague, London, England, 1664-1666',
 'A3AP4EXJT1R2W0': 'profileName: Joseph C. Jones [SEP] category: World War, 1939-1945, Executions and executioners',
 'A319KYEIAZ3SON': 'profileName: Mary Whipple [SEP] category: FICTION, Travel',
 'A26MQ4YGVS5CC2': 'profileName: Todd Bartholomew',
 'A2Y5DU0A0EKZB': 'profileName: Charles Reilly [SEP] category: Fiction',
 'A15OAXTD8A1FCS': 'profileName: F. Orion Pozo "Orion Pozo" [SEP] category: Juvenile Fiction, African American teenage girls',
 'AD033ETV5996N': 'profileName: Frank-Tommy Olsen [SEP] category: Fiction, Fiction',
 'AC7R1FF5P2PMG': 'profileName: William Cheng (poliwag_@hotmail.com)',
 'A12HCU3QCTQ2XT': 'profileName: "brukman" [SEP] category: Fiction, Fiction',
 'AL3KV6YU2S71Q': 'profileName: J. Angus Macdonald "bibliovore" [SEP] category: Fiction, Fiction, Crawford, Francis (Fictitious character)',
 'A1C384NS531WXA': 'profileName: Edward Gordon Brown [SEP] category: Fiction',
 'AJODIMJX61856': 'profileName: Rick Hunter',
 'AVHCWL9AHLEL9': 'profileName: Christopher Ware [SEP] category: Juvenile Fiction, Juvenile Fiction',
 'ALAQCCV155N0D': 'profileName: Chris Willett (cwillett@math.uiuc.edu) [SEP] category: Fiction',
 'AIVSFY6OL04GB': 'profileName: Author Bill Peschel "Writers Gone Wild" [SEP] category: Fiction',
 'A3DFH4CKPIT0N9': 'profileName: Suzanne Amara [SEP] category: History, Biography & Autobiography, Family & Relationships',
 'A2FWEZ0QS8N7A7': 'profileName: James Carragher',
 'A3PUUCN4LY499U': 'profileName: STRAWBYCAT@aol.com [SEP] category: Fiction, Fiction',
 'A1S193XFXZ6MNJ': 'profileName: Joan Mazza "Author, speaker, poet" [SEP] category: Fiction',
 'A15Q9YEG1XPEJN': 'profileName: Get What We Give [SEP] category: Fiction',
 'A8IZXBE7J6RNJ': 'profileName: P. B. Pereira [SEP] category: Juvenile Fiction, Birds',
 'A1BAGB0MH4ZVO1': 'profileName: Nelson Jimenez "nelsonzz" [SEP] category: Biography & Autobiography',
 'A3IS9FVR9WG5TY': 'profileName: Patrick J. Callahan',
 'A23GI8XN6XYTO3': 'profileName: mathilde de gardin "mathilde_de_gardin" [SEP] category: Fiction, Fiction',
 'AF0HOX2YGDIUT': 'profileName: Zane "NY Times Bestselling Author" [SEP] category: Fiction',
 'A1F54ZJJ8EOEA9': 'profileName: paiige@aol.com [SEP] category: Biography & Autobiography, Fiction',
 'A940CJE4B0AJ8': 'profileName: Darren in Kansas City "Darren in Kansas City" [SEP] category: Fiction',
 'A2G0IACKMUHH5F': 'profileName: J. B. Smith "smithjb23" [SEP] category: Body, Mind & Spirit',
 'A1P6NHUF7Q24E7': 'profileName: Jerry Dean [SEP] category: Comics & Graphic Novels, Science, Fiction',
 'ABANOHPDMIEYC': 'profileName: Daniel Krawisz [SEP] category: Great Britain',
 'A1WGUNNY90U041': 'profileName: Jon L. Albee "Faulkner Wannabe" [SEP] category: Architecture, Travel, Latvia',
 'AK81WLVD5KGUX': 'profileName: John S. Ryan "Scott Ryan" [SEP] category: Social Science, Fiction',
 'AD3ERWUV778YL': 'profileName: TJ [SEP] category: Ahab, Captain (Fictitious character), Historical fiction',
 'A1EQRMUPQICC3X': 'profileName: Phoebe',
 'A3M3ZSEP3JL3GS': 'profileName: Margaret Fiore [SEP] category: Fiction, Fiction, Travel',
 'APYAH4XBFQWLZ': 'profileName: Matthew Teng',
 'AYTGG6XTVUG7G': 'profileName: Douglas A. Greenberg [SEP] category: Juvenile Fiction',
 'AWIHJDPD4SCJB': 'profileName: Sharron Albert [SEP] category: Fiction',
 'ALN0TTRTLHA4E': 'profileName: Tom Munro "tomfrombrunswick" [SEP] category: Fiction, History, Exiles\' writings',
 'A1JWSDDIH5Z7DV': 'profileName: D. R. Schryer [SEP] category: Fiction, Biography & Autobiography',
 'A3AKPY4LXIC24O': 'profileName: Ryan Costantino [SEP] category: Fiction, Fiction',
 'A10M94ASQEBL56': 'profileName: D. Berdanis "endymion9" [SEP] category: Humor',
 'A1RLYOPK16YXC1': 'profileName: Stacey M Jones [SEP] category: Fiction, Fiction',
 'A1RAUVCWYHTQI4': 'profileName: A. Ross [SEP] category: Travel, History',
 'A3GFLNQE45KUMN': 'profileName: P. O\'Rourke "Patrick T. O\'Rourke" [SEP] category: Language Arts & Disciplines, History',
 'A3T0H5K8K5NEPH': 'profileName: muchadoaboutlisa@yahoo.com [SEP] category: Drama',
 'A3MQXFVZ9DCE8M': 'profileName: R. D. Allison (dallison@biochem.med.ufl.edu) [SEP] category: Education, Education, Fiction',
 'A1LSNQQ37FA5J9': 'profileName: Catspec "Catspec" [SEP] category: Social Science',
 'A53FKXES8SAD5': 'profileName: Naomi Johnson "beauvallet" [SEP] category: Fiction',
 'A37A44LEGU3T45': 'profileName: Todd Hudnall [SEP] category: Dispensationalism, Religion',
 'A1U0WO33TVDE9K': 'profileName: Wordsworth [SEP] category: Fiction, Copyright, Fiction',
 'A395QKQZ15GP4F': 'profileName: Lesley West [SEP] category: Fiction, Fiction',
 'A20HMA36ESANHC': 'profileName: Schmerguls "schmerguls" [SEP] category: Ethnology, Discernment of spirits, Cowboys',
 'A36S5U0QOWMOSX': 'profileName: Collin Garbarino [SEP] category: Fiction',
 'A76BSYHO794PI': 'profileName: Read [SEP] category: Fiction',
 'ADJKMC7AO7YN3': 'profileName: Jayson [SEP] category: Fiction, Fiction, Fiction',
 'AUY7L0SJNUM95': 'profileName: C. Sahu "Cathy Sahu" [SEP] category: Fiction, Germany, Conversion',
 'A6FIAB28IS79': 'profileName: Samuel Chell',
 'A1M36RIBC6IT7F': 'profileName: Elyon',
 'A1XX5797TIZT5Q': 'profileName: D. Mok [SEP] category: Fiction',
 'A33UDDOH82EROT': 'profileName: Rory Coker [SEP] category: Religion, Fiction',
 'A2UNOBCGU92K94': 'profileName: Chandler Merrell [SEP] category: Fiction, Families, Fiction',
 'A2K28JHMIY3XKZ': 'profileName: Charles Andrews [SEP] category: Fiction, Corporations',
 'A1D2AXVN20OQZD': 'profileName: Marc A. Coignard [SEP] category: Fiction',
 'A14UM7LOF20W6P': 'profileName: Frank [SEP] category: Social Science, Fiction',
 'A1EXS156IQG7OA': 'profileName: Mark R. Whittington [SEP] category: Music',
 'A3P60QO5L6XW87': 'profileName: Michael [SEP] category: Fiction, Character',
 'A9MAUO67ABVOB': 'profileName: F. Behrens "Frank Behrens" [SEP] category: Drama, Fiction',
 'A3NEN5NMJ78CWF': 'profileName: Lukas Jackson [SEP] category: Fiction',
 'A2L5XWA1DRCFAH': 'profileName: Akethan [SEP] category: Fiction, Fiction',
 'A3QYW1CL3A9L5P': 'profileName: Karen Kirsch "blazerlib" [SEP] category: Fiction, Fiction, Fiction',
 'A1PEKEZTSDJAVH': 'profileName: Eric San Juan [SEP] category: Fiction, Juvenile Fiction, Juvenile Fiction',
 'A222OLA2TGW1HW': 'profileName: J. F Malysiak "macafferty" [SEP] category: Comics & Graphic Novels, Fiction, Fiction',
 'A3FPS27DXXR2UA': 'profileName: Mark Valentine [SEP] category: Science, Fiction, Fiction',
 'AKZJW4ZRFTKZD': 'profileName: Robyn Lee Markow "webcat1" [SEP] category: Manhattan (New York, N.Y.), Catalogs, Union',
 'A3D7MHV6FTCKW7': 'profileName: H.S. Cross [SEP] category: Audiobooks, Fiction',
 'A2D1PE8NNJG2VE': 'profileName: Caroline [SEP] category: Fiction, Fiction',
 'A1VXG4DELT37C': 'profileName: Bernadette A. Moyer [SEP] category: Self-Help, Family & Relationships',
 'A9LIET7K21PAO': 'profileName: Thomas Stamper [SEP] category: Business & Economics, Business & Economics',
 'AKBH21PTTCWVJ': 'profileName: D. Bass [SEP] category: Art, Religion',
 'A3SGHQU56YHC2Y': 'profileName: David Savage [SEP] category: Self-Help',
 'AWNVA2PS0SYQS': 'profileName: ensiform [SEP] category: Fiction',
 'A1HW1Q3CDUWT75': 'profileName: A. Felton "voracious reader" [SEP] category: Fiction',
 'AK6ZI1TPK1B82': 'profileName: Marian Powell [SEP] category: Fiction, Juvenile Fiction',
 'A2VCGJLKGK2WJJ': 'profileName: Rebecca Herman [SEP] category: Juvenile Fiction, Juvenile Fiction, Juvenile Fiction',
 'AMQ37QNEIZCGS': 'profileName: DJ Rix [SEP] category: Poetry',
 'A2OGF3AOQIALBV': 'profileName: Harold Y. Grooms [SEP] category: History, History',
 'A1ZDDLHFSUGILJ': 'profileName: S. Clark [SEP] category: Education, Fiction',
 'A1AXHNRDJEQ0B': 'profileName: Adi Adler [SEP] category: Fiction, Biography & Autobiography',
 'A2DAAPYZTJ9PZA': 'profileName: C. Moon',
 'AGYSTKSZXYBR0': 'profileName: Tam Sesto [SEP] category: Fiction',
 'A39AWL2FKWDFK6': 'profileName: Cory D. Slipman [SEP] category: Families',
 'A26881C46IWAVB': 'profileName: An adult reader [SEP] category: Fiction',
 'A3CYDHL8RCOK6K': 'profileName: Joseph J. Janos III [SEP] category: Education, Political Science',
 'A37T1AYN11IGLH': 'profileName: "siammuse" [SEP] category: Biography & Autobiography',

In [53]:
# Combine movie features into a single string for each movie
items['categories'].fillna('', inplace=True)
items['authors'].fillna('', inplace=True)
items['cleaned_categories'] = items['categories'].str.strip('[]').str.replace("'", '')


# Define book_features with the specific condition
items['book_features'] = items.apply(
    lambda row: (
        f"title: {row['Title']} [SEP] category: {row['cleaned_categories']}"
        if row['cleaned_categories'] else
        f"title: {row['Title']}"
    ),
    axis=1
)

items['book_features']

C:\Users\Hooman\AppData\Local\Temp\ipykernel_25096\2261856678.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  items['categories'].fillna('', inplace=True)
C:\Users\Hooman\AppData\Local\Temp\ipykernel_25096\2261856678.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  items['authors'].fillna('', inplace=True)

0         title: Its Only Art If Its Well Hung! [SEP] ca...
1         title: Dr. Seuss: American Icon [SEP] category...
2         title: Wonderful Worship in Smaller Churches [...
3         title: Whispers of the Wicked Saints [SEP] cat...
4         title: Nation Dance: Religion, Identity and Cu...
                                ...
212399    title: The Orphan Of Ellis Island (Time Travel...
212400    title: Red Boots for Christmas [SEP] category:...
212401                                         title: Mamaw
212402     title: The Autograph Man [SEP] category: Fiction
212403    title: Student's Solutions Manual for Johnson/...
Name: book_features, Length: 206705, dtype: object

In [54]:
items['cleaned_categories']

0           Comics & Graphic Novels
1         Biography & Autobiography
2                          Religion
3                           Fiction
4
                    ...
212399             Juvenile Fiction
212400             Juvenile Fiction
212401
212402                      Fiction
212403
Name: cleaned_categories, Length: 206705, dtype: object

In [56]:
# Create a dictionary for fast lookup
item_features_dict = items.set_index('item_id')['book_features'].to_dict()

# Create lists of user and item texts
item_texts = [item_features_dict[itemId] for itemId in full_ratings['item_id'].unique()]

# Create a mapping from userId and movieId to indices
item_id_to_idx = {itemId: idx for idx, itemId in enumerate(full_ratings['item_id'].unique())}

# Map userId and movieId in ratings_df to indices
train_ratings['item_idx'] = train_ratings['item_id'].map(item_id_to_idx)

# Map userId and movieId in ratings_val to indices
val_ratings['item_idx'] = val_ratings['item_id'].map(item_id_to_idx)

# Map userId and movieId in ratings_test to indices
test_ratings['item_idx'] = test_ratings['item_id'].map(item_id_to_idx)

# Extract user indices, item indices, and ratings
train_item_indices = torch.LongTensor(train_ratings['item_idx'].values).to(device)
train_labels = torch.FloatTensor(train_ratings['rating'].values).to(device)

# Extract user indices, item indices, and ratings for validation
val_item_indices = torch.LongTensor(val_ratings['item_idx'].values).to(device)
val_labels = torch.FloatTensor(val_ratings['rating'].values).to(device)

# Extract user indices, item indices, and ratings for test
test_item_indices = torch.LongTensor(test_ratings['item_idx'].values).to(device)
test_labels = torch.FloatTensor(test_ratings['rating'].values).to(device)

In [57]:
len(test_labels)

36027

In [58]:
test_ratings

,Unnamed: 0.1,Unnamed: 0,item_id,Title,user_id,profileName,rating,timestamp,item_idx
0,36004,2971446,B000G167FA,Silver Pennies,AZUNT3QP2CWTL,"Ellen C. Falkenberry ""ellenf""",5.0,-1,0
1,27466,505724,B0006D9LII,Dance to the Piper,A3VVDE8I22IAJA,Charles Slovenski,5.0,868492800,13
2,21711,743724,B000NKUH32,NATHAN'S RUN.,A3AZ4O4I9S4668,"N. Sausser ""pucksau""",4.0,869270400,15
3,19484,642754,B000Q1RMUE,Eight Months on Ghazzah Street,A319KYEIAZ3SON,Mary Whipple,5.0,869702400,16
4,26662,1962743,B0006BV6RY,Wuthering Heights (College classics in English),A3SOB0CMUBK6XJ,fawls@erols.com,5.0,871084800,28
...,...,...,...,...,...,...,...,...,...
36022,3741,1247106,B000L5XWTA,Of Mice and Men,A1DKMAQDFN0UWA,Erez Davidi,3.0,1362009600,682
36023,28152,818057,B000CPSU9G,The Picture of Dorian Gray,A67VT05EV5EOF,Suzanne L. Goff,5.0,1362009600,1536
36024,14159,2283031,1844560333,Pride and Prejudice,A2GDT5QQSFZD14,Joy Hilda Handley,5.0,1362268800,409
36025,14160,936041,1593355548,Wuthering Heights,A2GDT5QQSFZD14,Joy Hilda Handley,5.0,1362268800,23
36026,14161,2525613,014013168X,The Buddha of Suburbia,A2GDT5QQSFZD14,Joy Hilda Handley,5.0,1362268800,4246

In [59]:
from torch.utils.data import Dataset, DataLoader

class CustomTextDataset(Dataset):
    def __init__(self, users, item_ids, ratings):
        self.users = users
        self.item_ids = item_ids
        self.ratings = ratings

    def __len__(self):
        return len(self.ratings)

    def __getitem__(self, idx):
        users = self.users[idx]
        item_id = self.item_ids[idx]
        rating = self.ratings[idx]
        return users, item_id, rating

In [60]:
# Create DataLoader for training data
train_dataset = CustomTextDataset(train_user_texts, train_item_indices, train_labels)
train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True, drop_last=True)

# Create DataLoader for validation data
val_dataset = CustomTextDataset(val_user_texts, val_item_indices, val_labels)
val_dataloader = DataLoader(val_dataset, batch_size=64, shuffle=True, drop_last=True)

# Create DataLoader for test data
test_dataset = CustomTextDataset(test_user_texts, test_item_indices, test_labels)
test_dataloader = DataLoader(test_dataset, batch_size=64, shuffle=True, drop_last=True)

In [63]:
class TwoTowerModel(pl.LightningModule):
    def __init__(self, user_model_name, item_model_name, embedding_size=768):
        super(TwoTowerModel, self).__init__()
        self.user_model = SentenceTransformer(user_model_name)
        self.item_model = SentenceTransformer(item_model_name)

        self.user_fc = nn.Linear(embedding_size, embedding_size)
        self.item_fc = nn.Linear(embedding_size, embedding_size)

        self.criterion = nn.MSELoss()
        self.epoch_losses = {'train_loss': [], 'val_loss': []}

    def forward(self, user_text, item_text):
        user_embedding = self.user_model.encode(user_text, convert_to_tensor=True).to(device)
        item_embedding = self.item_model.encode(item_text, convert_to_tensor=True).to(device)

        user_output = self.user_fc(user_embedding)
        item_output = self.item_fc(item_embedding)

        dot_product = torch.matmul(user_output.squeeze(), item_output.T)
        dot_product = 4 * torch.sigmoid(dot_product) + 1

        return dot_product

    def training_step(self, batch, batch_idx):
        users, items, ratings = batch

        items = [item_texts[i] for i in items.tolist()]

        preds = self(users, items)

        loss = self.criterion(preds, ratings)
        self.log('train_loss', loss)
        return loss

    def validation_step(self, batch, batch_idx):
        users, items, ratings = batch

        items = [item_texts[i] for i in items.tolist()]

        preds = self(users, items)

        loss = self.criterion(preds, ratings)
        self.log('val_loss', loss)
        return loss

    def configure_optimizers(self):
        return optim.Adam(self.parameters(), lr=1e-5)

class PrintLossesCallback(Callback):
    def on_train_epoch_end(self, trainer, pl_module):
        train_loss = trainer.callback_metrics.get('train_loss')
        if train_loss is not None:
            pl_module.epoch_losses['train_loss'].append(train_loss.item())
            print(f"Epoch {trainer.current_epoch + 1}: Train Loss: {train_loss.item()}")

    def on_validation_epoch_end(self, trainer, pl_module):
        val_loss = trainer.callback_metrics.get('val_loss')
        if val_loss is not None:
            pl_module.epoch_losses['val_loss'].append(val_loss.item())
            print(f"Epoch {trainer.current_epoch + 1}: Val Loss: {val_loss.item()}")

In [64]:
# model = TwoTowerModel(user_model_name='paraphrase-MiniLM-L6-v2', item_model_name='paraphrase-MiniLM-L6-v2')
# model = TwoTowerModel(user_model_name='paraphrase-MiniLM-L12-v2', item_model_name='paraphrase-MiniLM-L12-v2')
model = TwoTowerModel(user_model_name='all-mpnet-base-v2', item_model_name='all-mpnet-base-v2')

# Define the ModelCheckpoint callback
checkpoint_callback = ModelCheckpoint(
    monitor='val_loss',  # Metric to monitor
    dirpath='checkpoints/',  # Directory to save the checkpoints
    filename='with-history-best-checkpoint',  # Filename for the best model
    save_top_k=1,  # Save only the top 1 model
    mode='min'  # Mode to save the best model (min for validation loss)
)

trainer = pl.Trainer(max_epochs=5, log_every_n_steps=1, callbacks=[PrintLossesCallback()], enable_progress_bar=True)
trainer.fit(model, train_dataloader, val_dataloader)

# Print losses after training completes
print("Epoch losses:")
for epoch in range(trainer.max_epochs):
    train_loss = model.epoch_losses['train_loss'][epoch] if epoch < len(model.epoch_losses['train_loss']) else 'N/A'
    val_loss = model.epoch_losses['val_loss'][epoch] if epoch < len(model.epoch_losses['val_loss']) else 'N/A'
    print(f"Epoch {epoch + 1}: Train Loss: {train_loss}, Val Loss: {val_loss}")

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name       | Type                | Params | Mode
-----------------------------------------------------------
0 | user_model | SentenceTransformer | 109 M  | train
1 | item_model | SentenceTransformer | 109 M  | train
2 | user_fc    | Linear              | 590 K  | train
3 | item_fc    | Linear              | 590 K  | train
4 | criterion  | MSELoss             | 0      | train
-----------------------------------------------------------
220 M     Trainable params
0         Non-trainable params
220 M     Total params
880.616   Total estimated model params size (MB)

Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]

D:\Anaconda\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:475: Your `val_dataloader`'s sampler has shuffling enabled, it is strongly recommended that you turn shuffling off for val/test dataloaders.
D:\Anaconda\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.

Sanity Checking DataLoader 0:  50%|█████     | 1/2 [00:00<00:00,  4.50it/s]

D:\Anaconda\lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([64])) that is different to the input size (torch.Size([64, 64])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Sanity Checking DataLoader 0: 100%|██████████| 2/2 [00:00<00:00,  4.36it/s]Epoch 1: Val Loss: 2.6961781978607178

D:\Anaconda\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.

Epoch 0: 100%|██████████| 4098/4098 [25:41<00:00,  2.66it/s, v_num=5]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation:   0%|          | 0/510 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/510 [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 1/510 [00:00<03:02,  2.79it/s]
Validation DataLoader 0:   0%|          | 2/510 [00:00<03:19,  2.55it/s]
Validation DataLoader 0:   1%|          | 3/510 [00:01<03:36,  2.34it/s]
Validation DataLoader 0:   1%|          | 4/510 [00:01<03:35,  2.35it/s]
Validation DataLoader 0:   1%|          | 5/510 [00:02<03:36,  2.33it/s]
Validation DataLoader 0:   1%|          | 6/510 [00:02<03:36,  2.33it/s]
Validation DataLoader 0:   1%|▏         | 7/510 [00:03<03:41,  2.27it/s]
Validation DataLoader 0:   2%|▏         | 8/510 [00:03<03:55,  2.13it/s]
Validation DataLoader 0:   2%|▏         | 9/510 [00:04<04:08,  2.01it/s]
Validation DataLoader 0:   2%|▏         | 10/510 [00:05<04:18,  1.93it/s]
Validation DataLoader 0:   2%|▏         | 11/510 [00:05<04:25,  1.88it/s]
Validation DataLoader 0:   2%|▏         | 12/510 [00:06<04:33,  1.82it/s]
Validation DataLoader 0:   3%|▎         | 13/510 [00:07<04:36,  1.80it/s]
Validation DataLoader 0:   3%|▎         | 14/510 [00:07<04:40,  1.77it/s]
Validation DataLoader 0:   3%|▎         | 15/510 [00:08<04:42,  1.75it/s]
Validation DataLoader 0:   3%|▎         | 16/510 [00:08<04:36,  1.78it/s]
Validation DataLoader 0:   3%|▎         | 17/510 [00:09<04:37,  1.78it/s]
Validation DataLoader 0:   4%|▎         | 18/510 [00:09<04:32,  1.80it/s]
Validation DataLoader 0:   4%|▎         | 19/510 [00:10<04:29,  1.82it/s]
Validation DataLoader 0:   4%|▍         | 20/510 [00:10<04:26,  1.84it/s]
Validation DataLoader 0:   4%|▍         | 21/510 [00:11<04:23,  1.86it/s]
Validation DataLoader 0:   4%|▍         | 22/510 [00:11<04:20,  1.87it/s]
Validation DataLoader 0:   5%|▍         | 23/510 [00:12<04:17,  1.89it/s]
Validation DataLoader 0:   5%|▍         | 24/510 [00:12<04:14,  1.91it/s]
Validation DataLoader 0:   5%|▍         | 25/510 [00:13<04:19,  1.87it/s]
Validation DataLoader 0:   5%|▌         | 26/510 [00:14<04:21,  1.85it/s]
Validation DataLoader 0:   5%|▌         | 27/510 [00:14<04:19,  1.86it/s]
Validation DataLoader 0:   5%|▌         | 28/510 [00:15<04:19,  1.86it/s]
Validation DataLoader 0:   6%|▌         | 29/510 [00:15<04:17,  1.87it/s]
Validation DataLoader 0:   6%|▌         | 30/510 [00:15<04:15,  1.88it/s]
Validation DataLoader 0:   6%|▌         | 31/510 [00:16<04:13,  1.89it/s]
Validation DataLoader 0:   6%|▋         | 32/510 [00:16<04:12,  1.90it/s]
Validation DataLoader 0:   6%|▋         | 33/510 [00:17<04:10,  1.90it/s]
Validation DataLoader 0:   7%|▋         | 34/510 [00:17<04:09,  1.91it/s]
Validation DataLoader 0:   7%|▋         | 35/510 [00:18<04:08,  1.91it/s]
Validation DataLoader 0:   7%|▋         | 36/510 [00:18<04:07,  1.91it/s]
Validation DataLoader 0:   7%|▋         | 37/510 [00:19<04:05,  1.92it/s]
Validation DataLoader 0:   7%|▋         | 38/510 [00:19<04:03,  1.94it/s]
Validation DataLoader 0:   8%|▊         | 39/510 [00:20<04:02,  1.94it/s]
Validation DataLoader 0:   8%|▊         | 40/510 [00:20<04:01,  1.95it/s]
Validation DataLoader 0:   8%|▊         | 41/510 [00:20<04:00,  1.95it/s]
Validation DataLoader 0:   8%|▊         | 42/510 [00:21<03:59,  1.96it/s]
Validation DataLoader 0:   8%|▊         | 43/510 [00:21<03:57,  1.96it/s]
Validation DataLoader 0:   9%|▊         | 44/510 [00:22<03:56,  1.97it/s]
Validation DataLoader 0:   9%|▉         | 45/510 [00:22<03:55,  1.98it/s]
Validation DataLoader 0:   9%|▉         | 46/510 [00:23<03:53,  1.98it/s]
Validation DataLoader 0:   9%|▉         | 47/510 [00:23<03:52,  1.99it/s]
Validation DataLoader 0:   9%|▉         | 48/510 [00:24<03:51,  1.99it/s]
Validation DataLoader 0:  10%|▉         | 49/510 [00:24<03:50,  2.00it/s]
Validation DataLoader 0:  10%|▉         | 50/510 [00:24<03:49,  2.01it/s]
Validation DataLoader 0:  10%|█         | 51/510 [00:25<03:48,  2.01it/s]
Validation DataLoader 0:  10%|█         | 52/510 [00:25<03:47,  2.01it/s]
Validation DataLoader 0:  10%|█         | 53/510 [00:26<03:46,  2.02it/s]
Validation DataLoader 0:  11%|█         | 54/510 [00:26<03:44,  2.03it/s]
Validation DataLoader 0:  11%|█         | 55/510 [00:27<03:43,  2.03it/s]
Validation DataLoader 0:  11%|█         | 56/510 [00:27<03:43,  2.03it/s]
Validation DataLoader 0:  11%|█         | 57/510 [00:28<03:42,  2.03it/s]
Validation DataLoader 0:  11%|█▏        | 58/510 [00:28<03:41,  2.04it/s]
Validation DataLoader 0:  12%|█▏        | 59/510 [00:28<03:41,  2.04it/s]
Validation DataLoader 0:  12%|█▏        | 60/510 [00:29<03:41,  2.03it/s]
Validation DataLoader 0:  12%|█▏        | 61/510 [00:30<03:40,  2.03it/s]
Validation DataLoader 0:  12%|█▏        | 62/510 [00:30<03:39,  2.04it/s]
Validation DataLoader 0:  12%|█▏        | 63/510 [00:30<03:39,  2.04it/s]
Validation DataLoader 0:  13%|█▎        | 64/510 [00:31<03:38,  2.04it/s]
Validation DataLoader 0:  13%|█▎        | 65/510 [00:31<03:37,  2.05it/s]
Validation DataLoader 0:  13%|█▎        | 66/510 [00:32<03:36,  2.05it/s]
Validation DataLoader 0:  13%|█▎        | 67/510 [00:32<03:36,  2.05it/s]
Validation DataLoader 0:  13%|█▎        | 68/510 [00:33<03:35,  2.05it/s]
Validation DataLoader 0:  14%|█▎        | 69/510 [00:33<03:35,  2.05it/s]
Validation DataLoader 0:  14%|█▎        | 70/510 [00:34<03:34,  2.05it/s]
Validation DataLoader 0:  14%|█▍        | 71/510 [00:34<03:33,  2.05it/s]
Validation DataLoader 0:  14%|█▍        | 72/510 [00:35<03:33,  2.05it/s]
Validation DataLoader 0:  14%|█▍        | 73/510 [00:35<03:32,  2.05it/s]
Validation DataLoader 0:  15%|█▍        | 74/510 [00:35<03:31,  2.06it/s]
Validation DataLoader 0:  15%|█▍        | 75/510 [00:36<03:31,  2.06it/s]
Validation DataLoader 0:  15%|█▍        | 76/510 [00:36<03:30,  2.06it/s]
Validation DataLoader 0:  15%|█▌        | 77/510 [00:37<03:29,  2.07it/s]
Validation DataLoader 0:  15%|█▌        | 78/510 [00:37<03:28,  2.07it/s]
Validation DataLoader 0:  15%|█▌        | 79/510 [00:38<03:28,  2.07it/s]
Validation DataLoader 0:  16%|█▌        | 80/510 [00:38<03:27,  2.07it/s]
Validation DataLoader 0:  16%|█▌        | 81/510 [00:39<03:27,  2.07it/s]
Validation DataLoader 0:  16%|█▌        | 82/510 [00:39<03:26,  2.07it/s]
Validation DataLoader 0:  16%|█▋        | 83/510 [00:40<03:25,  2.07it/s]
Validation DataLoader 0:  16%|█▋        | 84/510 [00:40<03:25,  2.07it/s]
Validation DataLoader 0:  17%|█▋        | 85/510 [00:40<03:24,  2.08it/s]
Validation DataLoader 0:  17%|█▋        | 86/510 [00:41<03:23,  2.08it/s]
Validation DataLoader 0:  17%|█▋        | 87/510 [00:41<03:23,  2.08it/s]
Validation DataLoader 0:  17%|█▋        | 88/510 [00:42<03:22,  2.08it/s]
Validation DataLoader 0:  17%|█▋        | 89/510 [00:42<03:21,  2.08it/s]
Validation DataLoader 0:  18%|█▊        | 90/510 [00:43<03:21,  2.08it/s]
Validation DataLoader 0:  18%|█▊        | 91/510 [00:43<03:21,  2.08it/s]
Validation DataLoader 0:  18%|█▊        | 92/510 [00:44<03:20,  2.08it/s]
Validation DataLoader 0:  18%|█▊        | 93/510 [00:44<03:20,  2.08it/s]
Validation DataLoader 0:  18%|█▊        | 94/510 [00:45<03:19,  2.09it/s]
Validation DataLoader 0:  19%|█▊        | 95/510 [00:45<03:18,  2.09it/s]
Validation DataLoader 0:  19%|█▉        | 96/510 [00:45<03:18,  2.09it/s]
Validation DataLoader 0:  19%|█▉        | 97/510 [00:46<03:17,  2.09it/s]
Validation DataLoader 0:  19%|█▉        | 98/510 [00:46<03:17,  2.09it/s]
Validation DataLoader 0:  19%|█▉        | 99/510 [00:47<03:16,  2.09it/s]
Validation DataLoader 0:  20%|█▉        | 100/510 [00:47<03:16,  2.09it/s]
Validation DataLoader 0:  20%|█▉        | 101/510 [00:48<03:15,  2.09it/s]
Validation DataLoader 0:  20%|██        | 102/510 [00:48<03:14,  2.09it/s]
Validation DataLoader 0:  20%|██        | 103/510 [00:49<03:14,  2.10it/s]
Validation DataLoader 0:  20%|██        | 104/510 [00:49<03:13,  2.10it/s]
Validation DataLoader 0:  21%|██        | 105/510 [00:50<03:13,  2.10it/s]
Validation DataLoader 0:  21%|██        | 106/510 [00:50<03:12,  2.10it/s]
Validation DataLoader 0:  21%|██        | 107/510 [00:51<03:12,  2.10it/s]
Validation DataLoader 0:  21%|██        | 108/510 [00:51<03:11,  2.10it/s]
Validation DataLoader 0:  21%|██▏       | 109/510 [00:51<03:10,  2.10it/s]
Validation DataLoader 0:  22%|██▏       | 110/510 [00:52<03:10,  2.10it/s]
Validation DataLoader 0:  22%|██▏       | 111/510 [00:52<03:09,  2.10it/s]
Validation DataLoader 0:  22%|██▏       | 112/510 [00:53<03:09,  2.10it/s]
Validation DataLoader 0:  22%|██▏       | 113/510 [00:53<03:09,  2.10it/s]
Validation DataLoader 0:  22%|██▏       | 114/510 [00:54<03:08,  2.10it/s]
Validation DataLoader 0:  23%|██▎       | 115/510 [00:54<03:07,  2.10it/s]
Validation DataLoader 0:  23%|██▎       | 116/510 [00:55<03:07,  2.10it/s]
Validation DataLoader 0:  23%|██▎       | 117/510 [00:55<03:06,  2.10it/s]
Validation DataLoader 0:  23%|██▎       | 118/510 [00:56<03:06,  2.10it/s]
Validation DataLoader 0:  23%|██▎       | 119/510 [00:56<03:05,  2.10it/s]
Validation DataLoader 0:  24%|██▎       | 120/510 [00:56<03:05,  2.11it/s]
Validation DataLoader 0:  24%|██▎       | 121/510 [00:57<03:04,  2.11it/s]
Validation DataLoader 0:  24%|██▍       | 122/510 [00:57<03:04,  2.11it/s]
Validation DataLoader 0:  24%|██▍       | 123/510 [00:58<03:03,  2.11it/s]
Validation DataLoader 0:  24%|██▍       | 124/510 [00:58<03:03,  2.11it/s]
Validation DataLoader 0:  25%|██▍       | 125/510 [00:59<03:02,  2.11it/s]
Validation DataLoader 0:  25%|██▍       | 126/510 [00:59<03:02,  2.11it/s]
Validation DataLoader 0:  25%|██▍       | 127/510 [01:00<03:01,  2.11it/s]
Validation DataLoader 0:  25%|██▌       | 128/510 [01:00<03:01,  2.11it/s]
Validation DataLoader 0:  25%|██▌       | 129/510 [01:01<03:00,  2.11it/s]
Validation DataLoader 0:  25%|██▌       | 130/510 [01:01<03:00,  2.11it/s]
Validation DataLoader 0:  26%|██▌       | 131/510 [01:02<02:59,  2.11it/s]
Validation DataLoader 0:  26%|██▌       | 132/510 [01:02<02:58,  2.11it/s]
Validation DataLoader 0:  26%|██▌       | 133/510 [01:02<02:58,  2.11it/s]
Validation DataLoader 0:  26%|██▋       | 134/510 [01:03<02:57,  2.11it/s]
Validation DataLoader 0:  26%|██▋       | 135/510 [01:03<02:57,  2.11it/s]
Validation DataLoader 0:  27%|██▋       | 136/510 [01:04<02:57,  2.11it/s]
Validation DataLoader 0:  27%|██▋       | 137/510 [01:04<02:56,  2.11it/s]
Validation DataLoader 0:  27%|██▋       | 138/510 [01:05<02:55,  2.11it/s]
Validation DataLoader 0:  27%|██▋       | 139/510 [01:05<02:55,  2.12it/s]
Validation DataLoader 0:  27%|██▋       | 140/510 [01:06<02:54,  2.12it/s]
Validation DataLoader 0:  28%|██▊       | 141/510 [01:06<02:53,  2.12it/s]
Validation DataLoader 0:  28%|██▊       | 142/510 [01:06<02:53,  2.12it/s]
Validation DataLoader 0:  28%|██▊       | 143/510 [01:07<02:52,  2.12it/s]
Validation DataLoader 0:  28%|██▊       | 144/510 [01:07<02:52,  2.12it/s]
Validation DataLoader 0:  28%|██▊       | 145/510 [01:08<02:51,  2.12it/s]
Validation DataLoader 0:  29%|██▊       | 146/510 [01:08<02:51,  2.12it/s]
Validation DataLoader 0:  29%|██▉       | 147/510 [01:09<02:51,  2.12it/s]
Validation DataLoader 0:  29%|██▉       | 148/510 [01:09<02:50,  2.12it/s]
Validation DataLoader 0:  29%|██▉       | 149/510 [01:10<02:50,  2.12it/s]
Validation DataLoader 0:  29%|██▉       | 150/510 [01:10<02:49,  2.12it/s]
Validation DataLoader 0:  30%|██▉       | 151/510 [01:11<02:49,  2.12it/s]
Validation DataLoader 0:  30%|██▉       | 152/510 [01:11<02:48,  2.12it/s]
Validation DataLoader 0:  30%|███       | 153/510 [01:12<02:48,  2.12it/s]
Validation DataLoader 0:  30%|███       | 154/510 [01:12<02:47,  2.12it/s]
Validation DataLoader 0:  30%|███       | 155/510 [01:13<02:47,  2.12it/s]
Validation DataLoader 0:  31%|███       | 156/510 [01:13<02:46,  2.12it/s]
Validation DataLoader 0:  31%|███       | 157/510 [01:14<02:46,  2.12it/s]
Validation DataLoader 0:  31%|███       | 158/510 [01:14<02:45,  2.12it/s]
Validation DataLoader 0:  31%|███       | 159/510 [01:14<02:45,  2.12it/s]
Validation DataLoader 0:  31%|███▏      | 160/510 [01:15<02:45,  2.12it/s]
Validation DataLoader 0:  32%|███▏      | 161/510 [01:15<02:44,  2.12it/s]
Validation DataLoader 0:  32%|███▏      | 162/510 [01:16<02:43,  2.12it/s]
Validation DataLoader 0:  32%|███▏      | 163/510 [01:16<02:43,  2.13it/s]
Validation DataLoader 0:  32%|███▏      | 164/510 [01:17<02:42,  2.13it/s]
Validation DataLoader 0:  32%|███▏      | 165/510 [01:17<02:42,  2.13it/s]
Validation DataLoader 0:  33%|███▎      | 166/510 [01:18<02:41,  2.13it/s]
Validation DataLoader 0:  33%|███▎      | 167/510 [01:18<02:41,  2.13it/s]
Validation DataLoader 0:  33%|███▎      | 168/510 [01:18<02:40,  2.13it/s]
Validation DataLoader 0:  33%|███▎      | 169/510 [01:19<02:40,  2.13it/s]
Validation DataLoader 0:  33%|███▎      | 170/510 [01:19<02:39,  2.13it/s]
Validation DataLoader 0:  34%|███▎      | 171/510 [01:20<02:39,  2.13it/s]
Validation DataLoader 0:  34%|███▎      | 172/510 [01:20<02:38,  2.13it/s]
Validation DataLoader 0:  34%|███▍      | 173/510 [01:21<02:38,  2.13it/s]
Validation DataLoader 0:  34%|███▍      | 174/510 [01:21<02:37,  2.13it/s]
Validation DataLoader 0:  34%|███▍      | 175/510 [01:22<02:37,  2.13it/s]
Validation DataLoader 0:  35%|███▍      | 176/510 [01:22<02:36,  2.13it/s]
Validation DataLoader 0:  35%|███▍      | 177/510 [01:22<02:36,  2.13it/s]
Validation DataLoader 0:  35%|███▍      | 178/510 [01:23<02:35,  2.13it/s]
Validation DataLoader 0:  35%|███▌      | 179/510 [01:23<02:35,  2.13it/s]
Validation DataLoader 0:  35%|███▌      | 180/510 [01:24<02:34,  2.13it/s]
Validation DataLoader 0:  35%|███▌      | 181/510 [01:24<02:34,  2.13it/s]
Validation DataLoader 0:  36%|███▌      | 182/510 [01:25<02:33,  2.14it/s]
Validation DataLoader 0:  36%|███▌      | 183/510 [01:25<02:33,  2.14it/s]
Validation DataLoader 0:  36%|███▌      | 184/510 [01:26<02:32,  2.14it/s]
Validation DataLoader 0:  36%|███▋      | 185/510 [01:26<02:32,  2.14it/s]
Validation DataLoader 0:  36%|███▋      | 186/510 [01:27<02:31,  2.14it/s]
Validation DataLoader 0:  37%|███▋      | 187/510 [01:27<02:31,  2.14it/s]
Validation DataLoader 0:  37%|███▋      | 188/510 [01:27<02:30,  2.14it/s]
Validation DataLoader 0:  37%|███▋      | 189/510 [01:28<02:30,  2.14it/s]
Validation DataLoader 0:  37%|███▋      | 190/510 [01:28<02:29,  2.14it/s]
Validation DataLoader 0:  37%|███▋      | 191/510 [01:29<02:29,  2.14it/s]
Validation DataLoader 0:  38%|███▊      | 192/510 [01:29<02:28,  2.14it/s]
Validation DataLoader 0:  38%|███▊      | 193/510 [01:30<02:28,  2.14it/s]
Validation DataLoader 0:  38%|███▊      | 194/510 [01:30<02:27,  2.14it/s]
Validation DataLoader 0:  38%|███▊      | 195/510 [01:31<02:27,  2.14it/s]
Validation DataLoader 0:  38%|███▊      | 196/510 [01:31<02:26,  2.14it/s]
Validation DataLoader 0:  39%|███▊      | 197/510 [01:31<02:26,  2.14it/s]
Validation DataLoader 0:  39%|███▉      | 198/510 [01:32<02:25,  2.14it/s]
Validation DataLoader 0:  39%|███▉      | 199/510 [01:32<02:25,  2.14it/s]
Validation DataLoader 0:  39%|███▉      | 200/510 [01:33<02:24,  2.14it/s]
Validation DataLoader 0:  39%|███▉      | 201/510 [01:33<02:24,  2.14it/s]
Validation DataLoader 0:  40%|███▉      | 202/510 [01:34<02:23,  2.14it/s]
Validation DataLoader 0:  40%|███▉      | 203/510 [01:34<02:23,  2.14it/s]
Validation DataLoader 0:  40%|████      | 204/510 [01:35<02:22,  2.14it/s]
Validation DataLoader 0:  40%|████      | 205/510 [01:35<02:22,  2.14it/s]
Validation DataLoader 0:  40%|████      | 206/510 [01:36<02:21,  2.14it/s]
Validation DataLoader 0:  41%|████      | 207/510 [01:36<02:21,  2.14it/s]
Validation DataLoader 0:  41%|████      | 208/510 [01:37<02:20,  2.14it/s]
Validation DataLoader 0:  41%|████      | 209/510 [01:37<02:20,  2.14it/s]
Validation DataLoader 0:  41%|████      | 210/510 [01:37<02:19,  2.14it/s]
Validation DataLoader 0:  41%|████▏     | 211/510 [01:38<02:19,  2.14it/s]
Validation DataLoader 0:  42%|████▏     | 212/510 [01:38<02:18,  2.14it/s]
Validation DataLoader 0:  42%|████▏     | 213/510 [01:39<02:18,  2.15it/s]
Validation DataLoader 0:  42%|████▏     | 214/510 [01:39<02:18,  2.14it/s]
Validation DataLoader 0:  42%|████▏     | 215/510 [01:40<02:17,  2.14it/s]
Validation DataLoader 0:  42%|████▏     | 216/510 [01:40<02:17,  2.14it/s]
Validation DataLoader 0:  43%|████▎     | 217/510 [01:41<02:16,  2.14it/s]
Validation DataLoader 0:  43%|████▎     | 218/510 [01:41<02:16,  2.14it/s]
Validation DataLoader 0:  43%|████▎     | 219/510 [01:42<02:15,  2.14it/s]
Validation DataLoader 0:  43%|████▎     | 220/510 [01:42<02:15,  2.14it/s]
Validation DataLoader 0:  43%|████▎     | 221/510 [01:43<02:14,  2.14it/s]
Validation DataLoader 0:  44%|████▎     | 222/510 [01:43<02:14,  2.14it/s]
Validation DataLoader 0:  44%|████▎     | 223/510 [01:44<02:13,  2.14it/s]
Validation DataLoader 0:  44%|████▍     | 224/510 [01:44<02:13,  2.14it/s]
Validation DataLoader 0:  44%|████▍     | 225/510 [01:45<02:13,  2.14it/s]
Validation DataLoader 0:  44%|████▍     | 226/510 [01:45<02:12,  2.14it/s]
Validation DataLoader 0:  45%|████▍     | 227/510 [01:45<02:12,  2.14it/s]
Validation DataLoader 0:  45%|████▍     | 228/510 [01:46<02:11,  2.14it/s]
Validation DataLoader 0:  45%|████▍     | 229/510 [01:46<02:11,  2.14it/s]
Validation DataLoader 0:  45%|████▌     | 230/510 [01:47<02:10,  2.14it/s]
Validation DataLoader 0:  45%|████▌     | 231/510 [01:47<02:10,  2.14it/s]
Validation DataLoader 0:  45%|████▌     | 232/510 [01:48<02:09,  2.14it/s]
Validation DataLoader 0:  46%|████▌     | 233/510 [01:48<02:09,  2.14it/s]
Validation DataLoader 0:  46%|████▌     | 234/510 [01:49<02:08,  2.14it/s]
Validation DataLoader 0:  46%|████▌     | 235/510 [01:49<02:08,  2.14it/s]
Validation DataLoader 0:  46%|████▋     | 236/510 [01:50<02:07,  2.14it/s]
Validation DataLoader 0:  46%|████▋     | 237/510 [01:50<02:07,  2.14it/s]
Validation DataLoader 0:  47%|████▋     | 238/510 [01:51<02:06,  2.14it/s]
Validation DataLoader 0:  47%|████▋     | 239/510 [01:51<02:06,  2.14it/s]
Validation DataLoader 0:  47%|████▋     | 240/510 [01:51<02:05,  2.14it/s]
Validation DataLoader 0:  47%|████▋     | 241/510 [01:52<02:05,  2.14it/s]
Validation DataLoader 0:  47%|████▋     | 242/510 [01:52<02:04,  2.15it/s]
Validation DataLoader 0:  48%|████▊     | 243/510 [01:53<02:04,  2.15it/s]
Validation DataLoader 0:  48%|████▊     | 244/510 [01:53<02:03,  2.15it/s]
Validation DataLoader 0:  48%|████▊     | 245/510 [01:54<02:03,  2.15it/s]
Validation DataLoader 0:  48%|████▊     | 246/510 [01:54<02:02,  2.15it/s]
Validation DataLoader 0:  48%|████▊     | 247/510 [01:55<02:02,  2.15it/s]
Validation DataLoader 0:  49%|████▊     | 248/510 [01:55<02:02,  2.15it/s]
Validation DataLoader 0:  49%|████▉     | 249/510 [01:56<02:01,  2.15it/s]
Validation DataLoader 0:  49%|████▉     | 250/510 [01:56<02:01,  2.15it/s]
Validation DataLoader 0:  49%|████▉     | 251/510 [01:56<02:00,  2.15it/s]
Validation DataLoader 0:  49%|████▉     | 252/510 [01:57<02:00,  2.15it/s]
Validation DataLoader 0:  50%|████▉     | 253/510 [01:57<01:59,  2.14it/s]
Validation DataLoader 0:  50%|████▉     | 254/510 [01:58<01:59,  2.14it/s]
Validation DataLoader 0:  50%|█████     | 255/510 [01:58<01:58,  2.15it/s]
Validation DataLoader 0:  50%|█████     | 256/510 [01:59<01:58,  2.14it/s]
Validation DataLoader 0:  50%|█████     | 257/510 [01:59<01:57,  2.14it/s]
Validation DataLoader 0:  51%|█████     | 258/510 [02:00<01:57,  2.14it/s]
Validation DataLoader 0:  51%|█████     | 259/510 [02:00<01:57,  2.14it/s]
Validation DataLoader 0:  51%|█████     | 260/510 [02:01<01:56,  2.15it/s]
Validation DataLoader 0:  51%|█████     | 261/510 [02:01<01:56,  2.15it/s]
Validation DataLoader 0:  51%|█████▏    | 262/510 [02:02<01:55,  2.15it/s]
Validation DataLoader 0:  52%|█████▏    | 263/510 [02:02<01:55,  2.15it/s]
Validation DataLoader 0:  52%|█████▏    | 264/510 [02:02<01:54,  2.15it/s]
Validation DataLoader 0:  52%|█████▏    | 265/510 [02:03<01:54,  2.15it/s]

`Trainer.fit` stopped: `max_epochs=5` reached.

Epoch 4: 100%|██████████| 4098/4098 [34:58<00:00,  1.95it/s, v_num=5]
Epoch losses:
Epoch 1: Train Loss: 0.9101815819740295, Val Loss: 2.6961781978607178
Epoch 2: Train Loss: 0.8832100033760071, Val Loss: 0.9656608700752258
Epoch 3: Train Loss: 0.7956861257553101, Val Loss: 0.9606241583824158
Epoch 4: Train Loss: 0.9885196685791016, Val Loss: 0.9613440632820129
Epoch 5: Train Loss: 0.6481400728225708, Val Loss: 0.9564009308815002

In [20]:
model.epoch_losses

{'train_loss': [0.9391066431999207,
  1.0028347969055176,
  0.9369568824768066,
  0.9828064441680908,
  0.9409568905830383],
 'val_loss': [10.464865684509277,
  1.1707780361175537,
  1.138741135597229,
  1.120898962020874,
  1.1324385404586792,
  1.116618275642395]}

# Evaluation

In [65]:
# Assuming the training part has been done already, load the best model checkpoint


# best_model_path = './lightning_logs/paraphrase-MiniLM-L12-v2/not-binarized/user_title + store & item_ title + store  _ 5 epoch/checkpoints/epoch=4-step=435.ckpt'
best_model_path = './lightning_logs/version_5/checkpoints/epoch=4-step=20490.ckpt'

# best_model = TwoTowerModel.load_from_checkpoint(best_model_path, user_model_name='paraphrase-MiniLM-L6-v2', item_model_name='paraphrase-MiniLM-L6-v2').to(device)
# best_model = TwoTowerModel.load_from_checkpoint(best_model_path, user_model_name='paraphrase-MiniLM-L12-v2', item_model_name='paraphrase-MiniLM-L12-v2').to(device)
best_model = TwoTowerModel.load_from_checkpoint(best_model_path, user_model_name='all-mpnet-base-v2', item_model_name='all-mpnet-base-v2').to(device)

## Calculations

In [66]:
def get_top_n_items_without_history_unseen_items(model, userId, n):
    # Ensure the model is in evaluation mode
    model.eval()

    # Get the user text for the given userId
    user_text = val_last_user_texts[userId]
    # print(user_text)
    # Encode the user text
    user_embedding = model.user_model.encode(user_text, convert_to_tensor=True).to(device)

    # Compute the scores (dot product between user embedding and each item embedding)
    user_output = model.user_fc(user_embedding).to(device)
    item_output = model.item_fc(full_items_embeddings).to(device)
    dot_product = torch.matmul(user_output, item_output.t()).squeeze()

    # Get items the user has seen in the training and validation data
    seen_items_train = train_ratings[train_ratings['user_id'] == userId]['item_id'].values
    seen_items_val = val_ratings[val_ratings['user_id'] == userId]['item_id'].values
    seen_items = set(np.concatenate((seen_items_train, seen_items_val)))
    # print(dot_product)
    # print(len(dot_product), len(seen_items))
    # Get the top n + len(seen_items) item indices and their scores
    # top_n_scores, top_n_indices = torch.topk(dot_product, n + len(seen_items))
    top_n_scores, top_n_indices = torch.topk(dot_product, n)

    # Map indices back to item IDs
    top_n_item_ids = [list(item_id_to_idx.keys())[list(item_id_to_idx.values()).index(idx.item())] for idx in top_n_indices]
    # print(top_n_item_ids)
    # Filter out seen items
    # unseen_top_n_item_ids = [item for item in top_n_item_ids if item not in seen_items]
    # print(unseen_top_n_item_ids[:n])
    # return unseen_top_n_item_ids[:n]
    # print(top_n_item_ids[:n])
    return top_n_item_ids[:n]

In [67]:
item_texts[:20]

['title: Silver Pennies',
 'title: Playing for the Ashes [SEP] category: Fiction',
 'title: and ladies of the club [SEP] category: Fiction',
 'title: Bethlehem Road [SEP] category: Fiction',
 'title: Hercules, My Shipmate [SEP] category: Fiction',
 'title: HERCULES, MY SHIPMATE [SEP] category: Fiction',
 'title: Guns, Germs, and Steel: The Fates of Human Societies [SEP] category: History',
 'title: The Pathfinder [SEP] category: Fiction',
 'title: The Pathfinder - The Works of J. Fenimore Cooper [SEP] category: United States',
 'title: The Pathfinder, [SEP] category: Fiction',
 "title: The pathfinder (The modern readers' series) [SEP] category: Bumppo, Natty (Fictitious character)",
 'title: Cold Sassy Tree',
 'title: The King Must Die (Cardinal Giant GC-78)',
 'title: Dance to the Piper [SEP] category: Biography & Autobiography',
 'title: Dance to the piper (A Bantam giant)',
 "title: NATHAN'S RUN. [SEP] category: Fiction",
 'title: Eight Months on Ghazzah Street [SEP] category: Fiction',
 'title: East, West Stories',
 'title: Nature Printing: With Herbs, Fruits & Flowers',
 'title: Jack Nicklaus My Story [SEP] category: Biography & Autobiography']

In [68]:
# Assuming full_items_embeddings is already defined
full_items_embeddings = torch.stack([best_model.item_model.encode(item_text, convert_to_tensor=True) for item_text in item_texts]).to(device)

In [69]:
item_texts[8]

'title: The Pathfinder - The Works of J. Fenimore Cooper [SEP] category: United States'

## Type 0

In [70]:
def dcg(scores, k):
    scores = np.asfarray(scores)[:k]
    return np.sum(scores / np.log2(np.arange(2, scores.size + 2)))

def ndcg_at_k(labels, k):
    ideal_labels = sorted(labels, reverse=True)
    return dcg(labels, k) / dcg(ideal_labels, k)

def recall_at_k(labels, relevant_count, k):
    return np.sum(labels[:k]) / relevant_count

def mrr_at_k(labels, k):
    for i, label in enumerate(labels[:k]):
        if label == 1:
            return 1 / (i + 1)
    return 0

def evaluate_user_cf_model(model, test_data, k):
    ndcg_scores = []
    recall_scores = []
    mrr_scores = []

    # Get unique users
    unique_users = test_data['user_id'].unique()

    for user in unique_users:
        # print(user)
        # Get the top N items for the user, filtering out seen items
        recommended_items = get_top_n_items_without_history_unseen_items(model, user, k)
        # recommended_titles = [item_titles.get(item, "Unknown Title") for item in recommended_items]

        # print("Recommended items and their titles:")

        # for item, title in zip(recommended_items, recommended_titles):
        #     print(f"{item}: {title}")
        # recommended_items = ['1844560333', '1593355548', 'B000CPSU9G', '1901768600', 'B000NDSX6C', '158726398X', 'B000P3LVZA', 'B000N6DDJQ', 'B000L5XWTA', 'B0000CO4JZ']

        user_test_data = test_data[test_data['user_id'] == user]
        test_items = user_test_data['item_id'].values

        y_score = [1 if item in test_items else 0 for item in recommended_items]
        # print(y_score)
        ndcg = ndcg_at_k(y_score, k)
        recall = recall_at_k(y_score, len(test_items), k)
        mrr = mrr_at_k(y_score, k)

        ndcg_scores.append(ndcg)
        recall_scores.append(recall)
        mrr_scores.append(mrr)

    # avg_ndcg = np.mean(np.nan_to_num(ndcg_scores, nan=0.0))

    avg_ndcg = np.nanmean(ndcg_scores)
    avg_recall = np.nanmean(recall_scores)
    avg_mrr = np.nanmean(mrr_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg,
        'Recall@{}'.format(k): avg_recall,
        'MRR@{}'.format(k): avg_mrr,
    }

all_items = items['item_id'].unique()

eval_result = evaluate_user_cf_model(best_model, test_ratings, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model(best_model, test_ratings, k=10)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_25096\2329117254.py:7: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)
C:\Users\Hooman\AppData\Local\Temp\ipykernel_25096\2329117254.py:53: RuntimeWarning: Mean of empty slice
  avg_ndcg = np.nanmean(ndcg_scores)

{'NDCG@5': nan, 'Recall@5': 0.0, 'MRR@5': 0.0}
{'NDCG@10': 0.3286185913860017, 'Recall@10': 0.00011079455523899967, 'MRR@10': 4.39660933488094e-05}

In [ ]:
{'NDCG@5': 0.749980415767912, 'Recall@5': 0.000774772528200495, 'MRR@5': 0.0028648306426084205}

In [235]:
# Find the top 5 most repeated item_id
top_5_item_ids = full_ratings['item_id'].value_counts().head(10)

top_5_item_ids

item_id
1844560333    4079
1593355548    3105
B000CPSU9G    2634
1901768600    1908
B000NDSX6C    1879
158726398X    1843
B000P3LVZA    1644
B000N6DDJQ    1408
B000L5XWTA    1123
B0000CO4JZ    1120
Name: count, dtype: int64

## Type 2

In [71]:
def evaluate_user_cf_model(model, test_data, train_data, val_data, all_items, k):
    ndcg_scores = []

    # Get unique users
    unique_users = test_data['user_id'].unique()

    for user in unique_users:
        # Get the top N items for the user, filtering out seen items
        recommended_items = get_top_n_items_without_history_unseen_items(model, user, k)
        # recommended_items = ['1844560333', '1593355548', 'B000CPSU9G', '1901768600', 'B000NDSX6C']

        # recommended_items = ['1844560333', '1593355548', 'B000CPSU9G', '1901768600', 'B000NDSX6C', '158726398X', 'B000P3LVZA', 'B000N6DDJQ', 'B000L5XWTA', 'B0000CO4JZ']

        user_test_data = test_data[test_data['user_id'] == user]
        test_items = user_test_data['item_id'].values

        y_score = [
            user_test_data[user_test_data['item_id'] == item]['rating'].values[0] if item in test_items else 2.5
            for item in recommended_items
        ]

        ndcg = ndcg_at_k(y_score, k)
        ndcg_scores.append(ndcg)

    avg_ndcg = np.nanmean(ndcg_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg
    }

all_items = items['item_id'].unique()
# Evaluate the model
eval_result = evaluate_user_cf_model(best_model, test_ratings, train_ratings, val_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model(best_model, test_ratings, train_ratings, val_ratings, all_items, k=10)
print(eval_result)

{'NDCG@5': 1.0}
{'NDCG@10': 0.9999616618648126}

## Type 3

In [72]:
def evaluate_user_cf_model(model, test_data, k):
    ndcg_scores = []

    # Get unique users
    unique_users = test_data['user_id'].unique()

    for user in unique_users:
        # Get the top N items for the user, filtering out seen items
        recommended_items = get_top_n_items_without_history_unseen_items(model, user, k)
        # recommended_items = ['1844560333', '1593355548', 'B000CPSU9G', '1901768600', 'B000NDSX6C']
        # recommended_items = ['1844560333', '1593355548', 'B000CPSU9G', '1901768600', 'B000NDSX6C', '158726398X', 'B000P3LVZA', 'B000N6DDJQ', 'B000L5XWTA', 'B0000CO4JZ']

        user_test_data = test_data[test_data['user_id'] == user]
        test_items = user_test_data['item_id'].values
        # print(user)

        y_score = [
            user_test_data[user_test_data['item_id'] == item]['rating'].values[0] if item in test_items else 0
            for item in recommended_items
        ]

        ndcg = ndcg_at_k(y_score, k)
        ndcg_scores.append(ndcg)

    avg_ndcg = np.nanmean(ndcg_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg
    }

all_items = items['item_id'].unique()
# Evaluate the model
eval_result = evaluate_user_cf_model(best_model, test_ratings, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model(best_model, test_ratings, k=10)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_25096\2329117254.py:7: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)
C:\Users\Hooman\AppData\Local\Temp\ipykernel_25096\138295695.py:25: RuntimeWarning: Mean of empty slice
  avg_ndcg = np.nanmean(ndcg_scores)

{'NDCG@5': nan}
{'NDCG@10': 0.3286185913860017}

## Type 1

In [37]:
def evaluate_user_cf_model(model, test_data, train_data, val_data, all_items, k):
    ndcg_scores = []

    # Get unique users
    unique_users = test_data['user_id'].unique()

    for user in unique_users:
        # Get the top N items for the user, filtering out seen items
        recommended_items = get_top_n_items_without_history_unseen_items(model, user, k)

        user_test_data = test_data[test_data['user_id'] == user]
        test_items = user_test_data['item_id'].values
        # print(user)
        # y_score = [
        #     user_test_data[user_test_data['item_id'] == item]['rating'].values[0] if item in test_items else 0
        #     for item in recommended_items
        # ]
        y_score = [
            1 if (item in test_items and user_test_data[user_test_data['item_id'] == item]['rating'].values[0] == 1) else 0
            for item in recommended_items
        ]
        # y_score = [
        #     1 if (item in test_items and user_test_data[user_test_data['item'] == item]['label'].values[0] == 1) else 0
        #     for item in recommended_items
        # ]

        ndcg = ndcg_at_k(y_score, k)
        ndcg_scores.append(ndcg)

    # avg_ndcg = np.mean(np.nan_to_num(ndcg_scores, nan=0.0))
    avg_ndcg = np.nanmean(ndcg_scores)

    return {
        'NDCG@{}'.format(k): avg_ndcg
    }

all_items = items['item_id'].unique()
# Evaluate the model
eval_result = evaluate_user_cf_model(best_model, test_ratings, train_ratings, val_ratings, all_items, k=5)
print(eval_result)
eval_result = evaluate_user_cf_model(best_model, test_ratings, train_ratings, val_ratings, all_items, k=5)
print(eval_result)

C:\Users\Hooman\AppData\Local\Temp\ipykernel_25096\2329117254.py:7: RuntimeWarning: invalid value encountered in scalar divide
  return dcg(labels, k) / dcg(ideal_labels, k)

{'NDCG@5': 0.5088912804029996}

KeyboardInterrupt: